### ISSUE TITLE
default value with getGroupSelectFormForItem()

### ISSUE THREAD

**Issue by GregMage** [XOOPS/xmf#28]
I use this to display the permissions in my module. If I modify an article, no problem.

I would like to select all groups in this case! Like this:

![image](https://cloud.githubusercontent.com/assets/16707432/25563767/6e44bf56-2da3-11e7-8667-76bed881a9c3.png)

Right now it's like this:
![image](https://cloud.githubusercontent.com/assets/16707432/25563763/53c7a512-2da3-11e7-85a8-c5b56959c831.png)

It's a real plus!

Users do not need to check everything by default

**Comment by geekwright** [comment]
I can understand the intention here, but I have some concerns about this.

When using a group strategy of assigning multiple groups to a user to cumulatively add specific sets of access, this click saving concept could actually increase the effort.

As an example, suppose that in addition to the 3 standard groups, the admin adds REPORTER and EDITOR groups. For a news module, connection the user to the REPORTER group would provide submit permissions, while connection to the EDITOR group would provide additional editing and publication approvals.

A user in the REPORTER role would first be a REGISTERED USER which would provide the basics, i.e. accessing and reading news. The reporter user would also be added to the REPORTER group, which would provide the submit privilege.

Similarly, an editor user would get the basic access from being part of the REGISTERED USER group, and extra permissions from being part of the EDITOR group.

When this style of group management is used, there will be many groups, and most of them will be not be appropriate to any specific permission being edited.

This places the module author, and not the administrator, to decide on what is the most appropriate way to set default values. This will may give a small time savings for some cases, but can also lead to inconvenience and potential mistakes for other cases. 

I lean toward requiring intentional action by the administrator as preferable, as it is a more secure as a default.

**Comment by GregMage** [comment]
You're right, it's better to leave blank and add the necessary permissions. My idea was not good
