### ISSUE TITLE
\Xmf\Highlighter::apply() doesn't parse multiple spaces as expected

### ISSUE THREAD

**Issue by zyspec** [XOOPS/xmf#33]
If the input $words string has multiple contiguous spaces the apply() method generates empty $body[] array elements.  This has 'minimal' impact other than PHP throwing a warning (**_Warning: mb_stripos() [function.mb-stripos]: Empty delimiter in ..._**) but it would be better to use `preg_replace` instead of `str_replace`.  Just change:
```php
    public static function apply($words, $body, $pre = '<strong>', $post = '</strong>')
    {
        if (!is_array($words)) {
            $words = str_replace('  ', ' ', $words);
            $words = explode(' ', $words);
        }
        foreach ($words as $word) {
            $body = static::splitOnTag($word, $body, $pre, $post);
        }

        return $body;
    }
```
to:
```php
    public static function apply($words, $body, $pre = '<strong>', $post = '</strong>')
    {
        if (!is_array($words)) {
            $words = preg_replace('/[\s]+/', ' ', $words);
            $words = explode(' ', $words);
        }
        foreach ($words as $word) {
            $body = static::splitOnTag($word, $body, $pre, $post);
        }

        return $body;
    }

```
There is also a check in the `\Highlighter::splitOnTag()` method to verify if the mb_substr() function exists.  I think this check (and the non-mb_substr() conditional code) can be 'safely' removed since mb_substr() has been included in a standard PHP build for quite some time.
> Note: Anyone who is attempting to use the `Highlighter` class should be aware this implementation requires PHP 5.4.8 or greater.

**Comment by geekwright** [comment]
Actually, most extensions, including mbstring are separate packages in most Linux systems. While most hosting services include mbstring, there are many times it is not installed on client managed Debian and RedHat derived systems.

It is now safe to assume it is available as of 2.5.9 due to the inclusion of symfony/polyfill-mbstring. Eventually, we'll pull the old conditional code out, but I'm deferring that for right now. But, new code won't need to include any non-multibyte fallbacks.
