### ISSUE TITLE
truncateHtml()

### ISSUE THREAD

**Issue by GregMage** [XOOPS/xmf#58]
Is it possible to insert this function in XMF?

[https://github.com/XoopsModules25x/publisher/blob/master/class/Utility.php](https://github.com/XoopsModules25x/publisher/blob/master/class/Utility.php)

line 1431

I find this function interesting for modules

**Comment by geekwright** [comment]
I've been considering adding a string helper from Yii to XMF for a while. It is currently used for a similar capability to power the truncateHtml Smarty modifier added for 2.5.10. It was added directly into the Smarty plugin to keep it isolated while it was tested, just in case we needed/wanted to swap the implementation.

For details see:  https://github.com/XOOPS/XoopsCore25/pull/574

As far as I know it is working well. I like taking the Smarty approach because it pushes the choice of length to the theme where the designer can easily change it.

Once it was better proven, the idea was to move most of the BaseStringHandler class into an Xmf string helper, where the truncate functionality would be available outside of templates, too.

**Comment by GregMage** [comment]
101/5000
I had forgotten that. I also think it's the best solution to do it in the theme.
Thank you
