### ISSUE TITLE
Problem of PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [XOOPS/xmf#63]
As title, it seems that the PHP version requirements defined inside `require` and `require-dev` block in `composer.json` are different.

- In `require` block, the PHP version requirement defines the `"php": ">=5.3"`.
- In `require-dev` block, the PHP version requirement defines the `"phpunit/phpunit: ": "^7.0"`.
    - That is, the development environment requires `php-7.1` version at least.
- To make sure the XOOPS module framework can be compatible with `php-5.3` version at least, I recommend the we should test these PHP versions in development environment, too.

**Comment by geekwright** [comment]
Actually, that is intentional.

The workflow for Xmf starts in [XOOPS/XoopsCore](https://github.com/XOOPS/XoopsCore/tree/master/xoops_lib/Xmf) which has a minimum target of php-7,1. Changes to Xmf code are ported here for use in XoopsCore25, making any required changes for the environment. Before any PR is applied here, the code is inspected/static analysed to ensure it conforms to the PHP 5.3 minimum.

Tests in phpunit have evolved with each version, and PHP's rapid releases are creating big version gaps. This causes a lot of breaks and incompatibilities in the tests themselves. To take advantage of the newest improvements and still run in php 5.3 we would have to create a completely different test suite in phpunit v4. Rather than expend resources on back-porting unit tests, I've given priority to improving test coverage at the start of the workflow.

As a *forward compatibility* layer there is a need to meet the future on its terms.

**Comment by peter279k** [comment]
Hi @geekwright, thanks for your reply.

This issue will be closed because of your advanced explanation.
