### ISSUE TITLE
Proposal to have a slightly cleaner code by removing the @

### ISSUE THREAD

**Issue by montuy337513** [XOOPS/xmf#84]
For example, line 508 - Request.php
To replace :
`if (function_exists('get_magic_quotes_gpc') && @get_magic_quotes_gpc() && ($hash !== 'FILES')) {`

by 

` if (version_compare(PHP_VERSION, '7.4.0', '<') && function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() && ($hash !== 'FILES')) {`

**Comment by geekwright** [comment]
This is too close to being a non-issue to be changed.

For 2.5.11, there are polyfills supplied for the magic quotes functions that are used. The calls to the function are error suppressed to quiet the deprecation notice. We already know it is old crap that needs removed.

Adding a version check is not required. Generally, I prefer the exists checks if possible because they self document what is being tested. A version_compare could be thousands of things, while a function_exists is precisely one.

Once 2.5.12 is shipped all that gpc crap is going to be forever stripped from XOOPS.
